### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by moltar** [GaryB432/generator-lerna-typescript#1]
```
❯ yo lerna-typescript

     _-----_     ╭──────────────────────────╮
    |       |    │    Welcome to the rad    │
    |--(o)--|    │     lerna-typescript     │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

greeter coming right up
? Would you like to enable this option? Yes
events.js:173
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-lerna-typescript/generators/package/templates/tsconfig.json
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-lerna-typescript/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-lerna-typescript/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at module.exports.writing (/usr/local/lib/node_modules/generator-lerna-typescript/generators/package/index.js:27:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-lerna-typescript/node_modules/yeoman-generator/lib/index.js:399:25)
    at /usr/local/lib/node_modules/generator-lerna-typescript/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-lerna-typescript/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-lerna-typescript/node_modules/yeoman-generator/lib/index.js:400:11)
    at processImmediate (timers.js:632:19)
Emitted 'error' event at:
    at Immediate.setImmediate (/usr/local/lib/node_modules/generator-lerna-typescript/node_modules/yeoman-generator/lib/index.js:406:18)
    at processImmediate (timers.js:632:19)
```

**Comment by GaryB432** [comment]
hmm i seem to not have npm publish set up right.  working on it.

**Comment by GaryB432** [comment]
thanks for letting me know!  feel free to inform how it works out for your needs
